/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Basis: typeof import('./src/components/NoHi/components/Basis.vue')['default']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElRow: typeof import('element-plus/es')['ElRow']
    Format: typeof import('./src/components/NoHi/components/Format.vue')['default']
    Hooks: typeof import('./src/components/NoHi/components/Hooks.vue')['default']
    NoHi: typeof import('./src/components/NoHi/index.vue')['default']
    NoLayout: typeof import('./src/components/NoLayout/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
